{
 "title": "HAProxy - Monitoring",
 "time": { "from": "2026-08-31T10:14:29.309Z", "to": "2026-08-31T10:19:19.382Z" },
 "panels": [
  {
   "title": "Server UP per backend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_server_status{state=\"UP\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Richieste/sec per backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_backend_http_responses_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response code risposte HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latenza media backend (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}