apiVersion: v1
kind: Service
metadata:
  name: kong-status
  namespace: kong
  labels:
    app.kubernetes.io/name: kong-status
spec:
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: kong
  ports:
  - name: metrics
    port: 8100
    targetPort: 8100
---
# ServiceMonitor che dice a Prometheus di scrapare quel Service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kong
  selector:
    matchLabels:
      app.kubernetes.io/name: kong-status
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s