Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "nginx-fanout-proxy"

  config.vm.network "private_network", ip: "192.168.56.51"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.provision "file", source: "nginx.conf", destination: "/tmp/nginx.conf"

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    sudo apt-get update
    sudo apt-get install -y nginx

    cp /tmp/nginx.conf /etc/nginx/nginx.conf

    #valido la config e riavvio solo se essa è valida
    if nginx -t; then
      systemctl restart nginx
      systemctl enable nginx
      echo " == Nginx avviato correttamente =="
    else
      echo " == Errore nella configurazione di Nginx, non è stato avviato =="
      exit 1
    fi
  SHELL
end