Vagrant.configure("2") do |config|
    config.vm.box = "bento/rockylinux-10"
  config.vm.hostname = "rocky9Zabbix"

  config.vm.network "private_network", ip: "192.168.56.61"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "step1-rocky10-Zabbix7"
    vb.cpus = 2
    vb.memory = 3072
  end
end
