global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#il Collector: qui arrivano le metriche della applicazione
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

# Prometheus che scarppa se stesso: qui arrivano le metriche di Prometheus per vedere se è vivo.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

